### ISSUE TITLE
Code examples in list

### ISSUE THREAD

**Issue by michalbundyra** [laminas/documentation-theme#14]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | master

#### Summary

It looks like code samples are not rendered properly when used in lists.

See example at:
https://docs.mezzio.dev/mezzio/v3/features/router/aura/

<img width="683" alt="image" src="https://user-images.githubusercontent.com/7423207/71994026-f98f6f00-322f-11ea-960c-180c3b02d680.png">

**Comment by froschdesign** [comment]
Related to https://github.com/Python-Markdown/markdown/issues/53

**Comment by froschdesign** [comment]
We have to rework the entire documentation of this package, because I don't see any chance that the problem with Python Markdown will be fixed in the near future.

**Comment by michalbundyra** [comment]
... or we can do something similar what we have done for fenced code blocks.

**Comment by froschdesign** [comment]
Problems in:

### mezzio-mezzio

* https://docs.mezzio.dev/mezzio/v3/getting-started/quick-start/#creating-request-handler/
* https://docs.mezzio.dev/mezzio/v3/features/router/uri-generation/
* https://docs.mezzio.dev/mezzio/v3/features/router/aura/
* https://docs.mezzio.dev/mezzio/v3/features/template/twig/
* https://docs.mezzio.dev/mezzio/v3/features/helpers/url-helper/

### mezzio-authorization

* https://docs.mezzio.dev/mezzio-authorization/v1/auth-adapter/

**Comment by froschdesign** [comment]
@michalbundyra 
> …or we can do something similar what we have done for fenced code blocks.

Can you estimate how much effort it would take? Or is it easier to correct all code examples with problems?

**Comment by froschdesign** [comment]
@michalbundyra 
I invested some time in research and tested different configurations for the Markdown extensions.

This configuration works:

```yaml
markdown_extensions:
    - pymdownx.superfences:
    - toc:
        toc_depth: 2
```

Now code blocks can be used in blockquotes and lists:

````markdown
> ```php
  $foo = 'bar';
  ```

* 
  ```php
  $foo = 'bar';
  ```
````

Output:

```html
<blockquote>
<pre class="highlight"><code class="language-php">$foo = 'bar';</code></pre>
</blockquote>
<ul>
<li><pre class="highlight"><code class="language-php">$foo = 'bar';</code></pre></li>
</ul>
```

> If using a fenced block as the first line of a list, you will have to leave the first line blank, but remember that the list marker must be followed by a space.

https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#nested-fence-format

---

One problem I have found: the current markup for tabs no longer work. This means we have to rewrite all code examples in Markdown to use [the feature from Superfences](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/). The CSS must also be updated.

````markdown
## Using Currency Code

=== "Invoke Usage"
    ```php
    echo $this->currencyFormat(1234.56, 'EUR'); // '1.234,56 €'
    ```

=== "Setter Usage"
    ```php
    $this->plugin('currencyFormat')->setCurrencyCode('EUR');
    
    echo $this->currencyFormat(1234.56); // '1.234,56 €'
    ```
````

The configuration for MkDocs must be extended:

```yaml
markdown_extensions:
    - pymdownx.superfences:
    - pymdownx.tabbed:
    - toc:
        toc_depth: 2
```

I would do the rewrite.

https://github.com/search?q=org%3Alaminas+fct_label&type=Code

**Comment by michalbundyra** [comment]
@froschdesign great news!
I guess, we can extend this configuration "on build" as we want to have it for all repos and then we don't need modify each repo separately. RIght?

Ref: https://github.com/laminas/documentation-theme/blob/2403d39ae0c3db05711ec4b36aca1b9d96bc3e38/update_mkdocs_yml.py#L25-L35

**Comment by froschdesign** [comment]
> RIght?

Correct! 👍

**Comment by froschdesign** [comment]
Not to forget: **we must update all code examples in lists!**

**Comment by weierophinney** [comment]
This is great! It's nice to see that the tools we've been using have been evolving such that we can start removing our hacks and workarounds... and fix things we've never been able to!
