### ISSUE TITLE
Documentation sitemaps are invalid - missing module name in links

### ISSUE THREAD

**Issue by michalbundyra** [laminas/documentation-theme#16]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | master

#### Summary

https://github.com/mezzio/mezzio-hal/blob/gh-pages/sitemap.xml

WE have wrong links in all documentation sitemaps - there is missing module name part.

**Comment by froschdesign** [comment]
The `site_url` for MkDocs is set incorrectly. Instead of `https://docs.laminas.dev/` it must be `https://docs.laminas.dev/laminas-hydrator/`.
