### ISSUE TITLE
Documentation version switcher is not working

### ISSUE THREAD

**Issue by michalbundyra** [laminas/documentation-theme#17]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | master

#### Summary

Documentation version switcher is not working. When I try to check the version of the documentation I can see open the dropdown so I can't change the version.

See for example:
https://docs.mezzio.dev/mezzio-swoole/

Tried on Chrome and Safari.

**Comment by froschdesign** [comment]
Fixed with:

* https://github.com/laminas/laminas.github.io/pull/14
* #20
* #22
