### ISSUE TITLE
Feature request: link to migration and tutorials in topnav dropdown

### ISSUE THREAD

**Issue by weierophinney** [laminas/documentation-theme#19]
We currently link to each of the Laminas components, Laminas MVC, Mezzio, and Laminas API Tools documentation sections in the topnav dropdown item "All docs".

It'd be nice if we also linked to the Migration and Tutorials.

See also laminas/laminas.github.io#10

**Comment by froschdesign** [comment]
@weierophinney 
The current _simple_ dropdown will be transformed to bigger and nicer dropdown with separators and / or columns. There can we add the links.
