### ISSUE TITLE
Code examples unreadable

### ISSUE THREAD

**Issue by arueckauer** [laminas/documentation-theme#3]
#### Summary

The contrast of font and background color in the code examples is too low. It is a dark gray on a slightly less darker gray. It makes the code practical impossible to read.

#### Current behavior

As described...

![Code example](https://user-images.githubusercontent.com/1815979/71643505-f558d400-2cba-11ea-8146-d4b1880b95fb.png)

#### How to reproduce

Have a look at any code example in the documentation. All programming/scripting languages are affected, e.g. https://docs.laminas.dev/laminas-progressbar/adapters/#basic-example-for-the-client-side.

#### Expected behavior

A higher color contrast between font and background would greatly improve readability.

**Comment by froschdesign** [comment]
It looks like that MkDocs is the problem here. The rendered HTML is wrong:

```html
<p> <div class=codehilite><pre><span></span><span class=x>namespace MyModule\View\Helper;</span>

<span class=x>use Laminas\View\Helper\AbstractHelper;</span>

<span class=x>class SpecialPurpose extends AbstractHelper</span>
<span class=x>{</span>
<span class=x>    protected $count = 0;</span>

<span class=x>    public function __invoke()</span>
<span class=x>    {</span>
<span class=x>        $this-&gt;count++;</span>
<span class=x>        $output  = sprintf(&quot;I have seen &#39;The Jerk&#39; %d time(s).&quot;, $this-&gt;count);</span>
<span class=x>        $escaper = $this-&gt;getView()-&gt;plugin(&#39;escapehtml&#39;);</span>
<span class=x>        return $escaper($output);</span>
<span class=x>    }</span>
<span class=x>}</span>
</pre></div></p>
```

A code example in a `blockquote` is created correctly:

```html
<blockquote>
<pre class=codehilite><code class=language-php>
namespace MyModule\View\Helper;

use Laminas\View\Helper\EscapeHtml;

class SpecialPurpose
{
    private $count = 0;

    private $escaper;

    public function __construct(EscapeHtml $escaper)
    {
        $this-&gt;escaper = $escaper;
    }

    public function __invoke()
    {
        $this-&gt;count++;
        $output  = sprintf(&quot;I have seen 'The Jerk' %d time(s).&quot;, $this-&gt;count);
        $escaper = $this-&gt;escaper;
        return $escaper($output);
    }
}
</code></pre>
</blockquote>
```

See in documentation of laminas-view: https://docs.laminas.dev/laminas-view/helpers/advanced-usage/#writing-custom-helpers

I will investigate the problem further.

**Comment by weierophinney** [comment]
We have a fix ready for this, but it will take a few days to roll out. I'll drop a note in here when it's done.

**Comment by arueckauer** [comment]
Thank you! 👏🏻

**Comment by michalbundyra** [comment]
Whole documentation has been regenerated. We still have some small issues, but code samples are now readable. If you experience any other issue please report separate issue.

Thanks for reporting, @arueckauer !
