### ISSUE TITLE
Wrong link to blog feed in footer

### ISSUE THREAD

**Issue by froschdesign** [laminas/documentation-theme#38]
#### Current behavior

Redirects to a 404 error: https://getlaminas.org/blog/feed-rss.xml

#### How to reproduce

1. Go to https://docs.laminas.dev/
2. scroll down
3. click the feed link under support (fifth icon)

#### Expected behavior

The links to the blog feed are:

* https://getlaminas.org/blog/rss.xml
* https://getlaminas.org/blog/atom.xml

**Comment by weierophinney** [comment]
I've done two things:

- I've updated getlaminas.org to redirect the invalid URLs to the correct URLs.
- I've issued #39 to fix the issue in the templates.

Once all documentation is rebuilt, we can remove the getlaminas.org changes.
