### ISSUE TITLE
I as a newcomer did not understand the structure of the documentation

### ISSUE THREAD

**Issue by anhofmann** [laminas/documentation-theme#45]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I hope this is the right repository and form for my request. Please let me know when I should put this in another place.
Here is a screenshot of the page that I'm talking about: https://imgur.com/a/Aax2JYL

I am currently reading up on laminas and visiting the websites for it for the first time. I want to read through the documentation to understand how I can use Laminas. At https://docs.mezzio.dev/ I just clicked on https://docs.mezzio.dev/mezzio-problem-details/ to look at the documentation for the middleware. All I found was a guide how to install it with composer and links to the Github repo. On the github page I find the following about the documentation: " Documentation is in the doc tree, and can be compiled using mkdocs:
$ mkdocs build
You may also browse the documentation online."
The last line links back to https://docs.mezzio.dev/mezzio-problem-details/.

Only after a few minutes of clicking around I discovered that on the right side under the blue box is the table of contents of the documentation. 
It's just my personal opinion, but the whole right part was not visible to me as content because of the color choice of the design. This is grey text on a grey background and unconsciously gave me the signal that this part of the website is completely unimportant. It actually is the second most important part of the site, only with this one I can really read the documentation.

You could redesign the right part of the page. The blue box that calls for donations has the strongest color of the whole page and everything underneath is grey in grey. I think that this combination made me not understand how the page is built. The blue box could be made less present, the color could be weakened a little bit. And everything underneath could be given much more contrast. This way it would make it easier for a newcomer like me to get used to laminas.

**Comment by froschdesign** [comment]
@anhofmann 
Thanks for you important feedback!

> You could redesign the right part of the page.

Right, the entire sidebar needs a review and then a revision. We've identified a few other problems, the contrast ratio of the colour is one problem.

**Comment by froschdesign** [comment]
@anhofmann 
> The blue box could be made less present, the color could be weakened a little bit. And everything underneath could be given much more contrast.

The colours for headings and links in the sidebar have been updated and the [ratio between foreground and background colour](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast) was checked. 

The blue box that calls for donations works for us and as long as the goal is not reached, the box is still needed. 😃 

If you see any other problems, please feel free to report these. Thanks for your help! 👍
