### ISSUE TITLE
Links from search are missing component/package segment in URL

### ISSUE THREAD

**Issue by weierophinney** [laminas/documentation-theme#46]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | current

#### Summary

When searching for docs within a component, the URLs associated with search results include the text "mypage" in place of the actual component within the URL.

#### Current behavior

See above.

#### How to reproduce

1. Navigate to the laminas-view component documentation (https://docs.laminas.dev/laminas-view/)
1. Click on the "Search" icon in the top right (near the GitHub icon)
1. Type "basePath" into the search input
1. Click on the first result

#### Expected behavior

That the link would take me to https://docs.laminas.dev/laminas-view/helpers/base-path/

#### Actual behavior

The link took me to https://docs.laminas.dev/mypage/helpers/base-path/

**Comment by weierophinney** [comment]
@froschdesign I found the cause of the issue, and it is specific to this particular component (laminas-view).

The issue is that the search results include a reference to the BasePath view helper documentation. The search text associated with that page includes the following:

```html
<base href="/mypage/" />
```

Evidently, when creating the search text, mkdocs is stripping all tags... but leaves the contents of `<pre>` sections untouched, which means that when it goes to display that text, the HTML tags within are rendered verbatim, without any escaping. As a result, the base path for the page on which the search is performed is then changed on-the-fly, breaking all links going forward.

I think we need to file an issue upstream to the mkdocs project. In the meantime, I think we should likely post-process the `search_index.json` file to escape HTML in the `text` field of each search section.

**Comment by weierophinney** [comment]
I've hand-fixed the laminas-view docs using the escape script from #47 and pushed the changes, so that that search works correctly for that component.

**Comment by tempfirstuser** [comment]
@weierophinney , yes, it works now.

**Comment by tempfirstuser** [comment]
@weierophinney , but it still not working at https://docs.zendframework.com/zend-view/ (steps to recreate the issue is the same).

**Comment by weierophinney** [comment]
@tempfirstuser We're no longer updating the ZF documentation and repositories; they are all archived and marked read-only at this time. You'll note that you also get a notice at least once per week on the documentation sites indicating the project has moved.

**Comment by froschdesign** [comment]
@weierophinney 
> #### How to reproduce
> 1. Navigate to the laminas-view component documentation (https://docs.laminas.dev/laminas-view/)
> 2. Click on the "Search" icon in the top right (near the GitHub icon)
> 3. Type "basePath" into the search input
> 4. Click on the first result
> 
> #### Actual behavior
> The link took me to https://docs.laminas.dev/mypage/helpers/base-path/

I'm sorry but I can not reproduce this behaviour. All links work for me, in current and old documentation. No `mypage`:

```html
<div id="mkdocs-search-results">
    <article><h3><a href="./helpers/base-path/">BasePath</a></h3>
        <p>BasePath While most URLs generated by the framework have the base URL prepended automatically, developers will need to prepend the base URL to their
            own URLs (usually inside an href attribute) in orde
        </p>
    </article>
    <article><h3><a href="./helpers/base-path/#basepath">BasePath</a></h3>
        <p>While most URLs generated by the framework have the base URL prepended automatically, developers will need to prepend the base URL to their own URLs
            (usually inside an href attribute) in order for pat
        </p>
    </article>
    <article><h3><a href="./helpers/intro/#included-helpers">Included Helpers</a></h3>
        <p>Laminas comes with an initial set of helper classes. In particular, there are helpers for creating route-based URLs and HTML lists, as well as
            declaring variables. Additionally, there are a rich set o
        </p>
    </article>
    <article><h3><a href="./helpers/intro/">Introduction</a></h3>
        <p>Introduction In your view scripts, you'll perform certain complex functions over and over: e.g., formatting a date, generating form elements, or
            displaying action links. You can use helper, or plugin,
        </p>
    </article>
</div>
```

**Comment by tempfirstuser** [comment]
@froschdesign , it's because @weierophinney  have fixed it https://github.com/laminas/documentation-theme/issues/46#issuecomment-652511700

**Comment by froschdesign** [comment]
@tempfirstuser 
The pull request is still open and it works for me also for the old documentation.

**Comment by froschdesign** [comment]
@weierophinney 
Is this the same problem: https://github.com/mkdocs/mkdocs/issues/1744 ?

**Comment by weierophinney** [comment]
@froschdesign I can confirm the issue in docs.zendframework.com using the reproduce steps above. And the issue doesn't present in the above markup; it's because the `text` field of the related search item includes the markup, which is evidently evaluated within the DOM at some point, and thus emits a `<base href="/mypage/">` tag. This causes the `./` segment of those links to resolve to `/mypage/`, which you can confirm if you hover over or click on them.

And yes, I think it's essentially the same problem as the MkDocs issue you have linked. Using the post-processor script on the search index text fields resolves the issue entirely.

**Comment by froschdesign** [comment]
@weierophinney 
> …you can confirm if you hover over or click on them.

I'm afraid I can't confirm it. Everything works here. The links are looking good and the correct target page is loaded.
So I cannot confirm or reject your pull request but merge it if you think it resolves the problem.

**Comment by weierophinney** [comment]
> I'm afraid I can't confirm it. Everything works here.

Very odd! I've tried it in each of:

- Firefox on Linux
- Chrome on Linux
- Firefox on Android
- Chrome on Android

and each displays the errant behavior for me on the docs.zendframework.com domain! Since the problem is resolved for me on the laminas-view docs after applying the post-processor to the search index file, I'll go ahead and merge.
