### ISSUE TITLE
Support pushing documentation branches for release branches

### ISSUE THREAD

**Issue by Ocramius** [laminas/documentation-theme#48]
### Feature Request

Through https://github.com/laminas/automatic-releases, we will support release branches such as `1.0.x`, `1.1.x`, `2.0.x`, co-existing and independently maintained for each repo.

Currently, this repository works on the assumption that the `master` branch exists and will be used for documentation.

It would be a better idea to:

 1. check out the target repository
 2. check out each release branch
 3. build documentation for each release branch
 4. pick the latest release branch as "latest" documentation
 5. commit it
 6. push it

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

**Comment by Ocramius** [comment]
This seems to mostly affect this code location: https://github.com/laminas/documentation-theme/blob/d2654f6b50e398d75aeccad7e3aa973fa0ef7d63/github-actions/docs/entrypoint.sh#L79-L85

**Comment by weierophinney** [comment]
Regarding number (4): I'd argue, pick the latest release branch _for which a corresponding tag exists_, and mark that as the "latest" documentation. Otherwise, we run the risk of publishing documentation for unreleased code.

**Comment by Ocramius** [comment]
Makes sense: needs more bash-fu than I'm comfortable with though 😅

**Comment by weierophinney** [comment]
Fixed with #49.
